"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowUp, ChevronDown, ChevronLeft, ChevronUp, Clock3, Disc3, Heart, Headphones, ListMusic, ListOrdered, Music2, Pause, Play, Plus, Search, SlidersHorizontal, Sparkles, Trash2, UsersRound, X } from "lucide-react";
import { assetPath, artists, genres, getArtist, getGenre, getSong, songs, toPersianNumber, type Song } from "@/lib/music-data";
import { useMusic } from "@/components/music-provider";
import { ArtistCard, EmptyState, GenreCard, PlaylistCard, SectionHeading, SongCard, SongRow, VerifiedBadge } from "@/components/music-ui";

export function PageTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) {
  return <div className="page-title-block"><div>{eyebrow && <span className="page-eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action && <div className="page-title-action">{action}</div>}</div>;
}

const searchFilters = [{ id: "all", label: "همه" }, { id: "songs", label: "آهنگ‌ها" }, { id: "artists", label: "هنرمندان" }, { id: "albums", label: "آلبوم‌ها" }, { id: "playlists", label: "پلی‌لیست‌ها" }, { id: "genres", label: "ژانرها" }];

export function SearchPage() {
  const router = useRouter();
  const params = useSearchParams();
  const fromUrl = params.get("q") || "";
  const filterFromUrl = params.get("filter") || "all";
  const { searchQuery, setSearchQuery, saveSearch, recentSearches, clearSearches, playlists, playPlaylist } = useMusic();
  const [filter, setFilter] = useState(filterFromUrl);
  useEffect(() => { setSearchQuery(fromUrl); }, [fromUrl, setSearchQuery]);
  useEffect(() => { setFilter(filterFromUrl); }, [filterFromUrl]);
  const normalized = searchQuery.trim().toLocaleLowerCase();
  const matches = (value: string) => value.toLocaleLowerCase().includes(normalized);
  const foundSongs = normalized ? songs.filter((song) => matches(`${song.title} ${song.artist} ${song.album} ${song.genre}`)) : songs.slice(0, 7);
  const foundArtists = normalized ? artists.filter((artist) => matches(`${artist.name} ${artist.genres.join(" ")}`)) : artists.slice(0, 5);
  const foundPlaylists = normalized ? playlists.filter((playlist) => matches(`${playlist.name} ${playlist.description}`)) : playlists.slice(0, 4);
  const foundGenres = normalized ? genres.filter((genre) => matches(`${genre.name} ${genre.en}`)) : genres.slice(0, 6);
  const albumMap = new Map<string, Song>();
  songs.forEach((song) => { if (!albumMap.has(song.album)) albumMap.set(song.album, song); });
  const foundAlbums = [...albumMap.values()].filter((song) => !normalized || matches(`${song.album} ${song.artist}`)).slice(0, 6);
  const resultCount = foundSongs.length + foundArtists.length + foundPlaylists.length + foundGenres.length + foundAlbums.length;
  const visible = (id: string) => filter === "all" || filter === id;
  const chooseQuery = (value: string) => { setSearchQuery(value); saveSearch(value); router.push(`/search?q=${encodeURIComponent(value)}`); };
  const submit = (event: FormEvent) => { event.preventDefault(); saveSearch(searchQuery); router.replace(`/search${searchQuery.trim() ? `?q=${encodeURIComponent(searchQuery.trim())}` : ""}`); };
  return <div className="inner-page search-page page-enter"><PageTitle eyebrow="جستجو و کشف" title={normalized ? "نتایج جستجو" : "چی دوست داری بشنوی؟"} description={normalized ? `نتایج مرتبط با «${searchQuery}» رو پیدا کردیم.` : "دنیایی از صداهای تازه فقط یک جستجو با تو فاصله داره."} />
    <form className="search-page-form" onSubmit={submit}><Search size={22} /><input value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder="نام آهنگ، هنرمند، آلبوم یا حال‌وهوا..." autoFocus aria-label="جستجو" />{searchQuery && <button type="button" className="search-clear" onClick={() => { setSearchQuery(""); router.replace("/search"); }} aria-label="پاک کردن جستجو"><X size={18} /></button>}<button type="submit" className="gradient-btn">جستجو <ArrowLeft size={17} /></button></form>
    {!normalized && recentSearches.length > 0 && <div className="recent-searches"><div><span><Clock3 size={16} /> جستجوهای اخیر</span><button onClick={clearSearches}>پاک کردن همه</button></div><div className="chip-row">{recentSearches.map((item) => <button key={item} className="outline-chip" onClick={() => chooseQuery(item)}><Search size={14} />{item}</button>)}</div></div>}
    {!normalized && <div className="search-quick"><span>پیشنهاد برای جستجو:</span>{["آهنگ‌های آروم", "SZA", "الکترونیک", "احسان خواجه‌امیری"].map((item) => <button key={item} onClick={() => chooseQuery(item)}>{item} <ArrowLeft size={13} /></button>)}</div>}
    <div className="filter-bar"><div className="filter-chips">{searchFilters.map((item) => <button key={item.id} onClick={() => setFilter(item.id)} className={filter === item.id ? "selected" : ""}>{item.label}</button>)}</div><span><SlidersHorizontal size={16} /> {toPersianNumber(resultCount)} نتیجه</span></div>
    {normalized && resultCount === 0 ? <EmptyState icon={<Search size={30} />} title="نتیجه‌ای پیدا نشد" description="املای عبارت رو بررسی کن یا عبارت دیگه‌ای رو امتحان کن." action={<button className="gradient-btn" onClick={() => { setSearchQuery(""); router.replace("/search"); }}>دیدن پیشنهادها</button>} /> : <div className="search-results">
      {visible("songs") && foundSongs.length > 0 && <section className="result-section"><SectionHeading title={normalized ? "آهنگ‌ها" : "آهنگ‌های پرطرفدار"} subtitle={`${toPersianNumber(foundSongs.length)} آهنگ`} /><div className="track-list">{foundSongs.slice(0, filter === "all" ? 5 : 14).map((song, index) => <SongRow key={song.id} song={song} index={index} contextIds={foundSongs.map((item) => item.id)} />)}</div></section>}
      {visible("artists") && foundArtists.length > 0 && <section className="result-section"><SectionHeading title="هنرمندان" subtitle="صداهایی که دنبالشون بودی" /><div className="artist-grid">{foundArtists.map((artist) => <ArtistCard key={artist.id} artist={artist} />)}</div></section>}
      {visible("albums") && foundAlbums.length > 0 && <section className="result-section"><SectionHeading title="آلبوم‌ها" /><div className="album-grid">{foundAlbums.map((song) => <button key={song.album} className="album-card" onClick={() => playPlaylist(songs.filter((item) => item.album === song.album).map((item) => item.id))}><img src={song.cover} alt="" /><strong>{song.album}</strong><span>آلبوم · {song.artist}</span><span className="album-play"><Play size={18} fill="currentColor" /></span></button>)}</div></section>}
      {visible("playlists") && foundPlaylists.length > 0 && <section className="result-section"><SectionHeading title="پلی‌لیست‌ها" /><div className="playlist-grid">{foundPlaylists.map((playlist) => <PlaylistCard key={playlist.id} playlist={playlist} />)}</div></section>}
      {visible("genres") && foundGenres.length > 0 && <section className="result-section"><SectionHeading title="ژانرها" /><div className="genre-grid-home">{foundGenres.map((genre) => <GenreCard key={genre.id} genre={genre} small />)}</div></section>}
      {normalized && resultCount > 0 && !(["songs", "artists", "albums", "playlists", "genres"].some((id) => visible(id) && ({ songs: foundSongs.length, artists: foundArtists.length, albums: foundAlbums.length, playlists: foundPlaylists.length, genres: foundGenres.length } as Record<string, number>)[id] > 0)) && <EmptyState title="در این دسته نتیجه‌ای نیست" description="فیلتر دیگری رو امتحان کن." />}
    </div>}
  </div>;
}

export function ArtistsPage() {
  const { following, toggleFollow, playPlaylist } = useMusic();
  const featured = artists[0];
  return <div className="inner-page page-enter"><PageTitle eyebrow="هنرمندان" title="صداهایی که الهام‌بخشن" description="هنرمندان محبوبت رو دنبال کن و همیشه از تازه‌ترین آثارشون باخبر باش." /><section className="featured-artist" style={{ backgroundImage: `linear-gradient(90deg, rgba(9,12,27,.2),rgba(9,12,27,.72) 65%,#0b1022),url(${featured.banner})` }}><div className="featured-artist-content"><span className="featured-label"><Sparkles size={15} /> هنرمند منتخب هفته</span><h2>{featured.name} <VerifiedBadge /></h2><p>{featured.monthlyListeners} شنوندهٔ ماهانه</p><div><button className="gradient-btn" onClick={() => playPlaylist(songs.filter((song) => song.artistId === featured.id).map((song) => song.id))}><Play size={17} fill="currentColor" /> پخش آهنگ‌ها</button><button className="outline-btn" onClick={() => toggleFollow(featured.id)}>{following.includes(featured.id) ? "دنبال می‌کنی ✓" : "دنبال کردن"}</button></div></div></section><section className="catalog-section"><SectionHeading title="هنرمندان محبوب" subtitle="آشنا شو با صداهایی که همه دوست دارن" /><div className="artist-grid artist-grid-large">{artists.map((artist) => <ArtistCard key={artist.id} artist={artist} />)}</div></section></div>;
}

export function ArtistDetailPage({ id }: { id: string }) {
  const artist = getArtist(id);
  const { following, toggleFollow, playPlaylist, playlists } = useMusic();
  const [tab, setTab] = useState("songs");
  if (!artist) return <div className="inner-page"><EmptyState title="هنرمند پیدا نشد" description="شاید مسیر رو اشتباه اومدی." action={<Link className="gradient-btn" href="/artists">دیدن هنرمندان</Link>} /></div>;
  const artistSongs = songs.filter((song) => song.artistId === artist.id);
  const relatedPlaylists = playlists.filter((playlist) => playlist.songIds.some((songId) => artistSongs.some((song) => song.id === songId))).slice(0, 4);
  const albums = [...new Map(artistSongs.map((song) => [song.album, song])).values()];
  return <div className="inner-page artist-detail-page page-enter"><div className="artist-banner"><img src={artist.banner} alt="" /><div className="artist-banner-overlay" /><div className="artist-banner-content"><div className="artist-identity"><img src={artist.image} alt="" /><div><span className="page-eyebrow">{artist.verified ? "هنرمند تأییدشده" : "هنرمند"}</span><h1>{artist.name} {artist.verified && <VerifiedBadge />}</h1><p>{artist.monthlyListeners} شنوندهٔ ماهانه <span>·</span> {artist.followers} دنبال‌کننده</p></div></div><div className="artist-banner-actions"><button className="gradient-btn" onClick={() => playPlaylist(artistSongs.map((song) => song.id))}><Play size={18} fill="currentColor" /> پخش آهنگ‌ها</button><button className={`outline-btn ${following.includes(artist.id) ? "outline-btn-active" : ""}`} onClick={() => toggleFollow(artist.id)}>{following.includes(artist.id) ? "دنبال می‌کنی ✓" : "دنبال کردن"}</button></div></div></div>
    <div className="detail-tabs">{[{ id: "songs", label: "آهنگ‌ها" }, { id: "albums", label: "آلبوم‌ها" }, { id: "playlists", label: "پلی‌لیست‌ها" }, { id: "about", label: "درباره" }].map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>
    {tab === "songs" && <section className="catalog-section"><SectionHeading title="محبوب‌ترین آهنگ‌ها" subtitle="آهنگ‌هایی که بیشتر شنیده شدن" /><div className="track-list">{artistSongs.map((song, index) => <SongRow key={song.id} song={song} index={index} contextIds={artistSongs.map((item) => item.id)} />)}</div>{artistSongs.length === 0 && <EmptyState title="هنوز آهنگی اینجا نیست" description="به‌زودی آثار بیشتری اضافه می‌شن." />}</section>}
    {tab === "albums" && <section className="catalog-section"><SectionHeading title="آلبوم‌ها و تک‌آهنگ‌ها" /><div className="album-grid">{albums.map((song) => <button className="album-card" key={song.album} onClick={() => playPlaylist(artistSongs.filter((item) => item.album === song.album).map((item) => item.id))}><img src={song.cover} alt="" /><strong>{song.album}</strong><span>آلبوم · {artist.name}</span><span className="album-play"><Play size={18} fill="currentColor" /></span></button>)}</div></section>}
    {tab === "playlists" && <section className="catalog-section"><SectionHeading title="در پلی‌لیست‌ها" /><div className="playlist-grid">{relatedPlaylists.map((playlist) => <PlaylistCard key={playlist.id} playlist={playlist} />)}</div></section>}
    {tab === "about" && <div className="about-artist"><span className="page-eyebrow">داستان هنرمند</span><h2>دربارهٔ {artist.name}</h2><p>{artist.bio}</p><div className="artist-stats"><div><strong>{artist.followers}</strong><span>دنبال‌کننده</span></div><div><strong>{artist.monthlyListeners}</strong><span>شنوندهٔ ماهانه</span></div><div><strong>{toPersianNumber(artistSongs.length)}</strong><span>آهنگ</span></div></div><div className="tag-list">{artist.genres.map((genre) => <span key={genre}>{genre}</span>)}</div></div>}
  </div>;
}

export function GenresPage() {
  return <div className="inner-page page-enter"><PageTitle eyebrow="دنیای صداها" title="هر ژانر، یک دنیا" description="از ریتم‌های پرانرژی تا ملودی‌های آرام؛ موسیقی موردعلاقه‌ات رو اینجا پیدا کن." /><div className="genres-feature"><span className="genres-feature-orb"><Disc3 size={50} /></span><div><span>EXPLORE MUSIC</span><h2>سلیقه‌ات رو کشف کن</h2><p>یک ژانر انتخاب کن و سفرت رو در دنیای موسیقی شروع کن.</p></div><Sparkles size={30} /></div><section className="catalog-section"><SectionHeading title="همهٔ ژانرها" subtitle="کدوم صدا، صدای توئه؟" /><div className="genres-full-grid">{genres.map((genre) => <GenreCard key={genre.id} genre={genre} />)}</div></section></div>;
}

export function GenreDetailPage({ id }: { id: string }) {
  const genre = getGenre(id);
  const { playlists } = useMusic();
  if (!genre) return <div className="inner-page"><EmptyState title="ژانر پیدا نشد" description="می‌تونی ژانرهای دیگه رو ببینی." action={<Link className="gradient-btn" href="/genres">دیدن ژانرها</Link>} /></div>;
  const genreSongs = songs.filter((song) => song.genre.toLowerCase() === genre.en.toLowerCase());
  const shownSongs = genreSongs.length ? genreSongs : songs.slice(0, 5);
  const related = playlists.filter((playlist) => playlist.songIds.some((id) => shownSongs.some((song) => song.id === id))).slice(0, 4);
  return <div className="inner-page page-enter"><div className="genre-detail-hero" style={{ backgroundColor: genre.color }}><img src={genre.image} alt="" /><div><span className="page-eyebrow">کشف ژانر</span><h1>{genre.name}</h1><p>{genre.description}</p><span>{genre.en} · {toPersianNumber(genreSongs.length || shownSongs.length)} آهنگ</span></div></div><section className="catalog-section"><SectionHeading title={`آهنگ‌های ${genre.name}`} subtitle="بهترین انتخاب‌ها برای شروع" /><div className="track-list">{shownSongs.map((song, index) => <SongRow key={song.id} song={song} index={index} contextIds={shownSongs.map((item) => item.id)} />)}</div></section><section className="catalog-section"><SectionHeading title="پلی‌لیست‌های مرتبط" /><div className="playlist-grid">{related.map((playlist) => <PlaylistCard key={playlist.id} playlist={playlist} />)}</div></section></div>;
}

export function PlaylistsPage() {
  const { playlists, playlistFavorites, setCreatePlaylistOpen } = useMusic();
  const [filter, setFilter] = useState("all");
  const shown = playlists.filter((playlist) => filter === "all" || (filter === "favorites" && playlistFavorites.includes(playlist.id)) || (filter === "mine" && playlist.isCustom));
  return <div className="inner-page page-enter"><PageTitle eyebrow="پلی‌لیست‌ها" title="برای هر لحظه، یک پلی‌لیست" description="از آرامش صبحگاهی تا هیجان شب؛ صدای لحظه‌هات اینجاست." action={<button className="gradient-btn" onClick={() => setCreatePlaylistOpen(true)}><Plus size={18} /> ساخت پلی‌لیست</button>} /><div className="playlist-feature"><div className="playlist-feature-images"><img src={assetPath("/images/cover-good-days.jpg")} alt="" /><img src={assetPath("/images/cover-party.jpg")} alt="" /><img src={assetPath("/images/cover-lofi.jpg")} alt="" /></div><div><span className="page-eyebrow"><Sparkles size={15} /> انتخاب ویژهٔ Melody</span><h2>موسیقی برای هر حال‌وهوا</h2><p>پلی‌لیست‌هایی که با عشق چیده شدن، برای لحظه‌هایی که فقط موسیقی می‌تونه توصیفشون کنه.</p><Link href="/discover" className="outline-btn">پیشنهاد هوشمند <ArrowLeft size={16} /></Link></div></div><section className="catalog-section"><div className="section-heading"><div><h2>پلی‌لیست‌های محبوب</h2><p>{toPersianNumber(shown.length)} پلی‌لیست برای کشف</p></div><div className="small-filter-tabs">{[{ id: "all", label: "همه" }, { id: "favorites", label: "پسندیده‌شده" }, { id: "mine", label: "ساختهٔ من" }].map((item) => <button key={item.id} className={filter === item.id ? "active" : ""} onClick={() => setFilter(item.id)}>{item.label}</button>)}</div></div>{shown.length ? <div className="playlist-grid">{shown.map((playlist) => <PlaylistCard key={playlist.id} playlist={playlist} />)}</div> : <EmptyState icon={<ListMusic size={30} />} title="اینجا هنوز خالیه" description={filter === "mine" ? "اولین پلی‌لیست خودت رو بساز و آهنگ‌های محبوبت رو بهش اضافه کن." : "با زدن قلب کنار پلی‌لیست‌ها، اینجا پیداشون می‌کنی."} action={filter === "mine" ? <button className="gradient-btn" onClick={() => setCreatePlaylistOpen(true)}><Plus size={17} /> ساخت پلی‌لیست</button> : undefined} />}</section></div>;
}

export function PlaylistDetailPage({ id }: { id: string }) {
  const router = useRouter();
  const { playlists, playPlaylist, playlistFavorites, togglePlaylistFavorite, renamePlaylist, deletePlaylist, setCreatePlaylistOpen, addToPlaylist } = useMusic();
  const playlist = playlists.find((item) => item.id === id);
  const [renaming, setRenaming] = useState(false);
  const [name, setName] = useState("");
  const [adding, setAdding] = useState(false);
  const [songFilter, setSongFilter] = useState("");
  if (!playlist) return <div className="inner-page"><EmptyState title="پلی‌لیست پیدا نشد" description="شاید این پلی‌لیست حذف شده باشه." action={<Link className="gradient-btn" href="/playlists">دیدن پلی‌لیست‌ها</Link>} /></div>;
  const playlistSongs = playlist.songIds.map(getSong).filter((song): song is NonNullable<typeof song> => !!song);
  const addableSongs = songs.filter((song) => !playlist.songIds.includes(song.id) && `${song.title} ${song.artist}`.toLocaleLowerCase().includes(songFilter.toLocaleLowerCase()));
  const liked = playlistFavorites.includes(playlist.id);
  return <div className="inner-page playlist-detail-page page-enter"><div className="playlist-detail-hero"><img src={playlist.cover} alt="" /><div><span className="page-eyebrow">پلی‌لیست · {playlist.owner}</span><h1>{playlist.name}</h1><p>{playlist.description}</p><span>{toPersianNumber(playlistSongs.length)} آهنگ <span className="dot-sep">·</span> {toPersianNumber(playlist.likes)} پسند</span><div className="playlist-detail-actions"><button className="gradient-btn" onClick={() => playPlaylist(playlist.songIds)}><Play size={18} fill="currentColor" /> پخش پلی‌لیست</button><button className={`outline-btn ${liked ? "outline-btn-active" : ""}`} onClick={() => togglePlaylistFavorite(playlist.id)}><Heart size={17} fill={liked ? "currentColor" : "none"} /> {liked ? "پسندیده شد" : "پسندیدن"}</button><button className="outline-btn" onClick={() => { setName(playlist.name); setRenaming(true); }}>ویرایش نام</button></div></div></div>
    <section className="catalog-section"><SectionHeading title="آهنگ‌های این پلی‌لیست" subtitle="اینجا همه‌چیز به سلیقهٔ توئه" ><button className="outline-btn compact-outline" onClick={() => setAdding(true)}><Plus size={16} /> افزودن آهنگ</button></SectionHeading>{playlistSongs.length ? <div className="track-list">{playlistSongs.map((song, index) => <SongRow key={`${song.id}-${index}`} song={song} index={index} contextIds={playlist.songIds} playlistId={playlist.id} />)}</div> : <EmptyState icon={<Music2 size={28} />} title="هنوز آهنگی اینجا نیست" description="اولین آهنگ رو اضافه کن تا پلی‌لیستت جون بگیره." action={<button className="gradient-btn" onClick={() => setAdding(true)}><Plus size={17} /> افزودن آهنگ</button>} />}</section>
    {playlist.isCustom && <div className="playlist-danger"><span>دیگه به این پلی‌لیست نیاز نداری؟</span><button onClick={() => { if (window.confirm(`پلی‌لیست «${playlist.name}» حذف شود؟`)) { deletePlaylist(playlist.id); router.push("/playlists"); } }}><Trash2 size={16} /> حذف پلی‌لیست</button></div>}
    {renaming && <div className="modal-backdrop" onMouseDown={() => setRenaming(false)}><div className="modal-card create-modal" onMouseDown={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-label="تغییر نام پلی‌لیست"><button className="modal-close" onClick={() => setRenaming(false)}><X size={20} /></button><h2>تغییر نام پلی‌لیست</h2><p>یه اسم تازه برای حال‌وهوای موسیقیت انتخاب کن.</p><form onSubmit={(event) => { event.preventDefault(); if (name.trim()) { renamePlaylist(playlist.id, name); setRenaming(false); } }}><label>نام جدید<input value={name} onChange={(event) => setName(event.target.value)} maxLength={40} autoFocus required /></label><button className="gradient-btn" type="submit">ذخیرهٔ تغییرات</button></form></div></div>}
    {adding && <div className="modal-backdrop" onMouseDown={() => setAdding(false)}><div className="modal-card picker-modal add-songs-modal" onMouseDown={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-label="افزودن آهنگ"><button className="modal-close" onClick={() => setAdding(false)}><X size={20} /></button><span className="modal-eyebrow"><Plus size={16} /> پلی‌لیست {playlist.name}</span><h2>آهنگ اضافه کن</h2><p>آهنگ‌های موردعلاقه‌ات رو به این پلی‌لیست اضافه کن.</p><div className="modal-search"><Search size={17} /><input value={songFilter} onChange={(event) => setSongFilter(event.target.value)} placeholder="جستجوی آهنگ..." /></div><div className="picker-list">{addableSongs.map((song) => <button key={song.id} onClick={() => addToPlaylist(playlist.id, song.id)}><img src={song.cover} alt="" /><span><strong>{song.title}</strong><small>{song.artist}</small></span><Plus size={19} /></button>)}{addableSongs.length === 0 && <p className="picker-empty">آهنگ دیگری برای افزودن پیدا نشد.</p>}</div></div></div>}
  </div>;
}

export function LibraryPage() {
  const { playlists, favorites, recent, setCreatePlaylistOpen } = useMusic();
  const [tab, setTab] = useState("playlists");
  const mySongs = recent.map(getSong).filter((song): song is NonNullable<typeof song> => !!song);
  return <div className="inner-page page-enter"><PageTitle eyebrow="فضای شخصی تو" title="کتابخانهٔ من" description="همهٔ آهنگ‌ها و پلی‌لیست‌هایی که دوست داری، یک‌جا جمع شدن." action={<button className="gradient-btn" onClick={() => setCreatePlaylistOpen(true)}><Plus size={17} /> پلی‌لیست جدید</button>} /><div className="library-stats"><div><span className="stat-icon purple"><ListMusic size={23} /></span><strong>{toPersianNumber(playlists.length)}</strong><small>پلی‌لیست</small></div><div><span className="stat-icon pink"><Heart size={23} /></span><strong>{toPersianNumber(favorites.length)}</strong><small>آهنگ موردعلاقه</small></div><div><span className="stat-icon blue"><Clock3 size={23} /></span><strong>{toPersianNumber(recent.length)}</strong><small>آهنگ شنیده‌شده</small></div></div><div className="detail-tabs">{[{ id: "playlists", label: "پلی‌لیست‌های من" }, { id: "recent", label: "اخیراً پخش‌شده" }, { id: "favorites", label: "علاقه‌مندی‌ها" }].map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={tab === item.id ? "active" : ""}>{item.label}</button>)}</div>{tab === "playlists" && <div className="playlist-grid library-content">{playlists.map((playlist) => <PlaylistCard key={playlist.id} playlist={playlist} />)}</div>}{tab === "recent" && <div className="track-list library-content">{mySongs.map((song, index) => <SongRow key={song.id} song={song} index={index} contextIds={mySongs.map((item) => item.id)} />)}{mySongs.length === 0 && <EmptyState title="هنوز چیزی پخش نکردی" description="یه آهنگ بذار و سفر موسیقیت رو شروع کن." />}</div>}{tab === "favorites" && <div className="track-list library-content">{favorites.map(getSong).filter((song): song is NonNullable<typeof song> => !!song).map((song, index) => <SongRow key={song.id} song={song} index={index} contextIds={favorites} />)}{favorites.length === 0 && <EmptyState title="اینجا هنوز خالیه" description="با زدن قلب کنار آهنگ‌ها، اون‌ها رو اینجا نگه دار." />}</div>}</div>;
}

export function FavoritesPage() {
  const { favorites, playlistFavorites, playlists } = useMusic();
  const favoriteSongs = favorites.map(getSong).filter((song): song is NonNullable<typeof song> => !!song);
  const favoritePlaylists = playlists.filter((playlist) => playlistFavorites.includes(playlist.id));
  return <div className="inner-page page-enter"><PageTitle eyebrow="علاقه‌مندی‌های تو" title="چیزهایی که دوست داری" description="بهترین آهنگ‌ها و پلی‌لیست‌هات، همیشه در دسترس." /><section className="catalog-section"><SectionHeading title="آهنگ‌های پسندیده‌شده" subtitle={`${toPersianNumber(favoriteSongs.length)} آهنگ`} />{favoriteSongs.length ? <div className="track-list">{favoriteSongs.map((song, index) => <SongRow key={song.id} song={song} index={index} contextIds={favorites} />)}</div> : <EmptyState icon={<Heart size={30} />} title="هنوز آهنگی رو نپسندیدی" description="روی قلب کنار آهنگ‌های موردعلاقه‌ات بزن." action={<Link href="/search" className="gradient-btn">کشف آهنگ‌ها</Link>} />}</section><section className="catalog-section"><SectionHeading title="پلی‌لیست‌های پسندیده‌شده" /><div className="playlist-grid">{favoritePlaylists.map((playlist) => <PlaylistCard key={playlist.id} playlist={playlist} />)}</div>{favoritePlaylists.length === 0 && <EmptyState title="هنوز پلی‌لیستی رو نپسندیدی" description="از بین پلی‌لیست‌های Melody، موردعلاقه‌ات رو انتخاب کن." />}</section></div>;
}

export function QueuePage() {
  const { currentSong, queue, currentSongId, isPlaying, togglePlay, playSong, removeFromQueue, moveQueueItem } = useMusic();
  const currentIndex = queue.indexOf(currentSongId);
  const upcoming = currentIndex >= 0 ? queue.slice(currentIndex + 1) : queue.filter((id) => id !== currentSongId);
  return <div className="inner-page page-enter"><PageTitle eyebrow="موسیقی ادامه داره" title="صف پخش" description="آهنگ‌های بعدی رو ببین و ترتیب پخش رو به سلیقهٔ خودت بچین." /><div className="queue-now"><div className="queue-now-art"><img src={currentSong.cover} alt="" /></div><div><span className="page-eyebrow"><span className="live-dot live-dot-active" /> در حال پخش</span><h2>{currentSong.title}</h2><p>{currentSong.artist}</p><span>پیش‌نمایش آهنگ · {currentSong.album}</span><button className="gradient-btn" onClick={togglePlay}>{isPlaying ? <Pause size={18} fill="currentColor" /> : <Play size={18} fill="currentColor" />}{isPlaying ? "توقف پخش" : "ادامهٔ پخش"}</button></div></div><section className="catalog-section"><SectionHeading title="بعدی در صف" subtitle={`${toPersianNumber(upcoming.length)} آهنگ در انتظار`} />{upcoming.length ? <div className="queue-list">{upcoming.map((id, index) => { const song = getSong(id); if (!song) return null; return <div key={`${id}-${index}`} className="queue-item"><span className="row-index">{toPersianNumber(index + 1)}</span><button className="row-cover" onClick={() => playSong(song.id)}><img src={song.cover} alt="" /><span className="row-cover-play"><Play size={16} fill="currentColor" /></span></button><div className="row-main"><button className="row-title" onClick={() => playSong(song.id)}>{song.title}</button><span>{song.artist}</span></div><span className="row-time" dir="ltr">{song.duration}</span><div className="queue-actions"><button onClick={() => moveQueueItem(id, -1)} disabled={index === 0} aria-label="انتقال به بالا"><ChevronUp size={18} /></button><button onClick={() => moveQueueItem(id, 1)} disabled={index === upcoming.length - 1} aria-label="انتقال به پایین"><ChevronDown size={18} /></button><button onClick={() => removeFromQueue(id)} aria-label="حذف از صف"><X size={18} /></button></div></div>; })}</div> : <EmptyState icon={<ListOrdered size={30} />} title="صف پخشت خالیه" description="از منوی کنار هر آهنگ، اون رو به صف پخش اضافه کن." action={<Link className="gradient-btn" href="/search">کشف آهنگ‌ها</Link>} />}</section></div>;
}
